theme: jekyll-theme-minimal

title: Dr Salaheddin Darwish

description: BEng(Hons), MRes, PhD, AFHEA - Personal Website

logo: https://avatars2.githubusercontent.com/u/37536214?s=400&u=eba7657251ab1e7de4bb07260e3d064437e10e26&v=4
